---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: storage
spec:
  storageClassName: manual
  accessModes:
   - ReadWriteOnce 
  capacity:
    storage: 10Gi
  hostPath: 
    path: /mnt/data
...
