---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-rs
  labels:
    type: appserver
    author: intellqiit
spec:
  replicas: 1
  selector:
    matchLabels:
     type: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        type: appserver
    spec:
     containers:
       - name: mytmcat
         image: tomee
         ports:
          - containerPort: 8080
            hostPort: 8080
...
