---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip
  labels:
    auhtor: intelliqit
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
   type: db
   author: intelliqit
...
