apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-retain-waitforconsumer
  resources:
    requests:
      storage: 3Gi
