---
apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
  name: my-storageclass
provisioner: kuberentes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
...
